---
- name: Copy Grafana deb package
  copy:
    src: "{{ playbook_dir }}/../files/grafana_10.4.1_amd64.deb"
    dest: /tmp/grafana_10.4.1_amd64.deb
    mode: '0644'

- name: Install Grafana
  apt:
    deb: /tmp/grafana_10.4.1_amd64.deb
    state: present

- name: Enable and start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Wait for Grafana to start
  wait_for:
    port: 3000
    timeout: 30